// Fallback content used when the database is empty (e.g., first preview).
// Real content is the same shape as `projects` / `plugins` / `services` rows.

export const SEED_PLUGINS = [
  {
    slug: "ogxevents",
    name: "OGXEvents",
    tagline: "Team-based Minecraft event engine with GUI, arenas, and rewards.",
    description:
      "Advanced Minecraft event management system with team-based events, admin controls, arena systems, countdowns, rewards, event GUI, and configurable event logic.",
    plugin_type: "Event System",
    version: "1.4.0",
    price_type: "Free",
    status: "ACTIVE",
    featured: true,
    supported_versions: ["1.20.x", "1.21.x"],
    features: [
      "Event creation",
      "Team management",
      "Arena setup",
      "Countdown system",
      "Rewards",
      "Admin start/stop commands",
      "Event GUI",
      "Configurable messages",
      "Scoreboard/event status",
      "Spectator support",
    ],
    dependencies: [],
    commands: [],
    permissions: [],
    changelog: [],
    gallery: [],
  },
  {
    slug: "ogxfairpvp",
    name: "OGxFairPvP",
    tagline: "Smart 1v1 combat lock that blocks PvP interference.",
    description:
      "When two players fight, others cannot interfere until combat inactivity ends. Useful for FFA arenas and survival PvP zones.",
    plugin_type: "PvP Protection",
    version: "1.2.0",
    price_type: "Free",
    status: "ACTIVE",
    featured: true,
    supported_versions: ["1.20.x", "1.21.x"],
    features: [
      "1v1 combat lock",
      "Anti-interference system",
      "Combat timeout",
      "Admin bypass",
      "Arena/region support",
      "Actionbar warnings",
      "Configurable cooldowns",
    ],
    dependencies: [],
    commands: [],
    permissions: [],
    changelog: [],
    gallery: [],
  },
  {
    slug: "ogxauthpro",
    name: "OGxAuthPro",
    tagline: "Authentication and account protection for cracked servers.",
    description:
      "Advanced Minecraft authentication and account protection system for cracked/offline-mode servers with login/register flow, session protection, security checks, and admin controls.",
    plugin_type: "Authentication",
    version: "2.0.0",
    price_type: "Free",
    status: "ACTIVE",
    featured: true,
    supported_versions: ["1.20.x", "1.21.x"],
    features: [
      "Register/login system",
      "Session protection",
      "Security checks",
      "Admin reset commands",
      "Cracked server support",
      "Configurable messages",
    ],
    dependencies: [],
    commands: [],
    permissions: [],
    changelog: [],
    gallery: [],
  },
  {
    slug: "kithub",
    name: "KitHub",
    tagline: "Modern kit vault and loadout GUI plugin.",
    description:
      "Modern kit vault and armor/loadout management plugin with GUI-based kit storage, armor switching, organized kit slots, and survival/PvP server support.",
    plugin_type: "Kit / Loadout",
    version: "1.1.0",
    price_type: "Free",
    status: "ACTIVE",
    featured: true,
    supported_versions: ["1.20.x", "1.21.x"],
    features: [
      "Kit vault GUI",
      "Armor/loadout storage",
      "Fast switching",
      "Organized slots",
      "Permissions",
      "Modern GUI",
      "Server-friendly storage",
    ],
    dependencies: [],
    commands: [],
    permissions: [],
    changelog: [],
    gallery: [],
  },
  {
    slug: "arctixchampionship",
    name: "ArctixChampionship",
    tagline: "Tournament and championship engine for Minecraft.",
    description:
      "Competitive Minecraft championship/event system for structured tournaments, teams, match flow, score tracking, rounds, and event administration.",
    plugin_type: "Tournament",
    version: "1.0.0",
    price_type: "Free",
    status: "ACTIVE",
    featured: false,
    supported_versions: ["1.20.x", "1.21.x"],
    features: [
      "Tournament system",
      "Team brackets",
      "Round tracking",
      "Score system",
      "Admin controls",
      "Event status display",
    ],
    dependencies: [],
    commands: [],
    permissions: [],
    changelog: [],
    gallery: [],
  },
  {
    slug: "ogxanticheat",
    name: "OGxAntiCheat",
    tagline: "Movement and combat anti-cheat with staff alerts.",
    description:
      "Minecraft anti-cheat system focused on suspicious movement/combat detection, alerts, logs, staff tools, and configurable checks.",
    plugin_type: "Anti-Cheat",
    version: "0.9.0",
    price_type: "Free",
    status: "CONCEPT",
    featured: false,
    supported_versions: ["1.20.x", "1.21.x"],
    features: [
      "Staff alerts",
      "Movement checks",
      "Combat checks",
      "Logs",
      "Configurable checks",
      "Violation levels",
    ],
    dependencies: [],
    commands: [],
    permissions: [],
    changelog: [],
    gallery: [],
  },
  {
    slug: "girigo-v1",
    name: "Girigo v1",
    tagline: "Early experimental utility plugin by FighterPlayz.",
    description:
      "Early custom Minecraft plugin/system project by FighterPlayz. An experimental legacy project with basic server utility features.",
    plugin_type: "Utility",
    version: "1.0.0",
    price_type: "Free",
    status: "ARCHIVED",
    featured: false,
    supported_versions: ["1.19.x"],
    features: ["Basic server utilities", "Command framework", "Config loader"],
    dependencies: [],
    commands: [],
    permissions: [],
    changelog: [],
    gallery: [],
  },
];

export const SEED_PROJECTS = [
  // Minecraft servers
  {
    slug: "arctixmc",
    title: "ArctixMC",
    category: "server",
    short_description:
      "Survival/PvP Minecraft network with ranks, kits, GUIs, events and coin engine.",
    full_description:
      "Survival/PvP Minecraft server ecosystem with ranks, kits, GUIs, events, crates, CoinEngine systems, TAB, DeluxeMenus, optimization, and a custom server experience.",
    tech_stack: ["Paper", "DeluxeMenus", "Velocity", "TAB", "CoinEngine"],
    features: ["Ranks", "Kits", "GUI shops", "Coin engine", "Tournaments", "Optimization"],
    status: "ACTIVE",
    featured: true,
    sort_order: 1,
  },
  {
    slug: "ogxnetwork",
    title: "OGxNetwork",
    category: "server",
    short_description:
      "Velocity-based proxy network with backend servers, Votifier, and MOTD systems.",
    full_description:
      "Minecraft network/server infrastructure project involving Velocity, backend servers, Votifier, MOTD, proxy setup, plugins, and server systems.",
    tech_stack: ["Velocity", "Paper", "Votifier", "Redis", "MariaDB"],
    features: ["Proxy routing", "Backend servers", "Votifier", "Custom MOTD"],
    status: "ACTIVE",
    featured: true,
    sort_order: 2,
  },
  {
    slug: "bloodmc-server",
    title: "BloodMC",
    category: "server",
    short_description: "Minecraft server build with branding and server-side setup.",
    full_description:
      "Minecraft server project worked on by FighterPlayz, including website/server-side setup, branding, and Minecraft server presentation.",
    tech_stack: ["Paper", "DeluxeMenus", "Pterodactyl"],
    features: ["Server setup", "Plugin config", "Branding"],
    status: "MAINTAINED",
    featured: false,
    sort_order: 3,
  },
  // Websites
  {
    slug: "loftix-host",
    title: "Loftix Host",
    category: "website",
    short_description:
      "Modern hosting brand site with plans, sponsorship banners, and gaming-host style UI.",
    full_description:
      "Hosting company website/brand work with modern hosting presentation, plans, sponsorship banners, and gaming-host style UI.",
    tech_stack: ["Next.js", "Tailwind", "Stripe"],
    features: ["Plans grid", "Sponsorship", "Checkout"],
    status: "ACTIVE",
    featured: true,
    sort_order: 4,
  },
  {
    slug: "sevenstar-travel",
    title: "Sevenstar Travelling",
    category: "website",
    short_description:
      "Travel company website with packages, booking and professional travel design.",
    full_description:
      "Sevenstar Adventures Holidays Pvt. Ltd. — travel company website with homepage, about page, packages, booking/contact sections, package showcase, sliders, and professional travel design.",
    tech_stack: ["React", "Tailwind", "Supabase"],
    features: ["Package showcase", "Booking form", "Sliders"],
    status: "ACTIVE",
    featured: true,
    sort_order: 5,
  },
  {
    slug: "ogxdevs",
    title: "OGxDevs",
    category: "website",
    short_description: "Developer team brand site for Minecraft, web and plugin work.",
    full_description:
      "Developer team/brand website for Minecraft, web, plugin, and systems development.",
    tech_stack: ["TanStack Start", "Tailwind", "Supabase"],
    features: ["Team showcase", "Portfolio", "Contact"],
    status: "ACTIVE",
    featured: true,
    sort_order: 6,
  },
  {
    slug: "ogxnodes",
    title: "OGxNodes",
    category: "website",
    short_description: "Hosting plans website with VPS and Minecraft hosting tiers.",
    full_description:
      "Hosting plans website/project with VPS and Minecraft hosting plans, pricing cards, sliders, and hosting-focused sections.",
    tech_stack: ["Next.js", "Tailwind", "Stripe"],
    features: ["Plans", "VPS pricing", "Sliders"],
    status: "ACTIVE",
    featured: false,
    sort_order: 7,
  },
  {
    slug: "bloodmc-site",
    title: "BloodMC Website",
    category: "website",
    short_description: "Gaming-style site for the BloodMC Minecraft server.",
    full_description:
      "Minecraft server website/branding project with gaming-style layout and server presentation.",
    tech_stack: ["React", "Tailwind"],
    features: ["Server presentation", "Branding", "Store hooks"],
    status: "MAINTAINED",
    featured: false,
    sort_order: 8,
  },
  // Systems / concepts
  {
    slug: "lifesteal-system",
    title: "LifeSteal System",
    category: "system",
    short_description: "LifeSteal SMP mechanic with heart drops and bans on zero hearts.",
    full_description:
      "LifeSteal Minecraft system with heart-based PvP economy, bans on elimination, heart recipes, and configurable mechanics.",
    tech_stack: ["Paper", "Java"],
    features: ["Heart drops", "Auto-ban", "Recipes", "Config"],
    status: "ACTIVE",
    featured: false,
    sort_order: 9,
  },
  {
    slug: "coin-shop-systems",
    title: "Coin Shop & Daily Rewards",
    category: "system",
    short_description: "Coin shop, daily rewards and playtime rewards bundle.",
    full_description:
      "Coin shop systems, daily reward systems, playtime rewards, and custom DeluxeMenus GUIs.",
    tech_stack: ["DeluxeMenus", "CoinEngine", "PlaceholderAPI"],
    features: ["Coin shop", "Daily rewards", "Playtime rewards", "GUIs"],
    status: "ACTIVE",
    featured: false,
    sort_order: 10,
  },
  {
    slug: "ai-npc-assistant",
    title: "AI NPC Server Assistant",
    category: "system",
    short_description: "Concept AI NPC that answers questions in-game using an LLM.",
    full_description:
      "Concept AI NPC server assistant: an in-game NPC powered by an LLM to answer player questions, help new players, and surface rules.",
    tech_stack: ["Paper", "Gemini", "WebSocket"],
    features: ["LLM responses", "Rules helper", "New player onboarding"],
    status: "CONCEPT",
    featured: false,
    sort_order: 11,
  },
  {
    slug: "mc-optimization",
    title: "Minecraft Optimization Setups",
    category: "system",
    short_description: "Paper/Pufferfish tuning, Velocity setup and Pterodactyl deployment.",
    full_description:
      "Server optimization, Paper/Pufferfish tuning, Velocity setup, Pterodactyl setup, plugin configuration, GUIs, scoreboards, TAB, menus, ranks and event systems.",
    tech_stack: ["Paper", "Pufferfish", "Velocity", "Pterodactyl"],
    features: ["Paper tuning", "Velocity", "Pterodactyl", "TAB/Scoreboard"],
    status: "ACTIVE",
    featured: false,
    sort_order: 12,
  },
];

export const SEED_SERVICES = [
  {
    slug: "plugin-development",
    title: "Plugin Development",
    description: "Custom Spigot/Paper plugins built clean, configurable and performant.",
    features: ["Java + Paper API", "Config-driven", "GUI menus", "Permissions/commands"],
    icon: "Code2",
    starting_price: "from $40",
    active: true,
  },
  {
    slug: "server-optimization",
    title: "Server Optimization",
    description: "Paper/Pufferfish tuning, lag fixes, async profiling and bottleneck removal.",
    features: ["spark profiling", "Async chunk tuning", "TPS recovery", "Memory tuning"],
    icon: "Cpu",
    starting_price: "from $30",
    active: true,
  },
  {
    slug: "network-setup",
    title: "Network / Proxy Setup",
    description: "Velocity proxies, backend servers and Pterodactyl deployments.",
    features: ["Velocity routing", "Pterodactyl", "Votifier", "MOTD systems"],
    icon: "Server",
    starting_price: "from $60",
    active: true,
  },
  {
    slug: "web-development",
    title: "Web Development",
    description: "Modern, fast, animated websites for servers, brands and hosting companies.",
    features: ["React / TanStack", "Tailwind", "Supabase", "SEO"],
    icon: "Globe",
    starting_price: "from $80",
    active: true,
  },
];

export const SEED_SKILLS = [
  { name: "Java / Paper API", category: "Plugin Dev", level: 92, description: "Spigot/Paper plugin development.", sort_order: 1 },
  { name: "Velocity / Proxy", category: "Infra", level: 85, description: "Proxy routing and backend wiring.", sort_order: 2 },
  { name: "Pterodactyl", category: "Infra", level: 88, description: "Server panel deployment.", sort_order: 3 },
  { name: "DeluxeMenus", category: "Plugin Dev", level: 95, description: "GUI menu engineering.", sort_order: 4 },
  { name: "Paper Tuning", category: "Optimization", level: 90, description: "TPS recovery and tuning.", sort_order: 5 },
  { name: "React / TanStack", category: "Web", level: 80, description: "Modern web stacks.", sort_order: 6 },
  { name: "Tailwind CSS", category: "Web", level: 90, description: "Design systems.", sort_order: 7 },
  { name: "Supabase / Postgres", category: "Backend", level: 78, description: "Postgres + RLS + edge.", sort_order: 8 },
  { name: "Node / Bun", category: "Backend", level: 80, description: "TypeScript backend services.", sort_order: 9 },
];