/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebsitesRouteImport } from './routes/websites'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ServersRouteImport } from './routes/servers'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PluginsRouteImport } from './routes/plugins'
import { Route as HireRouteImport } from './routes/hire'
import { Route as EcosystemRouteImport } from './routes/ecosystem'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as PluginsSlugRouteImport } from './routes/plugins.$slug'
import { Route as AdminTicketsRouteImport } from './routes/admin.tickets'
import { Route as AdminTestimonialsRouteImport } from './routes/admin.testimonials'
import { Route as AdminSkillsRouteImport } from './routes/admin.skills'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminPluginsRouteImport } from './routes/admin.plugins'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'

const WebsitesRoute = WebsitesRouteImport.update({
  id: '/websites',
  path: '/websites',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersRoute = ServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsRoute = PluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const HireRoute = HireRouteImport.update({
  id: '/hire',
  path: '/hire',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemRoute = EcosystemRouteImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjectsRoute,
} as any)
const PluginsSlugRoute = PluginsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PluginsRoute,
} as any)
const AdminTicketsRoute = AdminTicketsRouteImport.update({
  id: '/admin/tickets',
  path: '/admin/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/admin/testimonials',
  path: '/admin/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSkillsRoute = AdminSkillsRouteImport.update({
  id: '/admin/skills',
  path: '/admin/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/admin/services',
  path: '/admin/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/admin/reviews',
  path: '/admin/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/admin/projects',
  path: '/admin/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPluginsRoute = AdminPluginsRouteImport.update({
  id: '/admin/plugins',
  path: '/admin/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/admin/messages',
  path: '/admin/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/admin/blog',
  path: '/admin/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/admin/announcements',
  path: '/admin/announcements',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/announcements': typeof AnnouncementsRoute
  '/contact': typeof ContactRoute
  '/ecosystem': typeof EcosystemRoute
  '/hire': typeof HireRoute
  '/plugins': typeof PluginsRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/reviews': typeof ReviewsRoute
  '/servers': typeof ServersRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tickets': typeof TicketsRoute
  '/websites': typeof WebsitesRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/plugins': typeof AdminPluginsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/skills': typeof AdminSkillsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/plugins/$slug': typeof PluginsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/announcements': typeof AnnouncementsRoute
  '/contact': typeof ContactRoute
  '/ecosystem': typeof EcosystemRoute
  '/hire': typeof HireRoute
  '/plugins': typeof PluginsRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/reviews': typeof ReviewsRoute
  '/servers': typeof ServersRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tickets': typeof TicketsRoute
  '/websites': typeof WebsitesRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/plugins': typeof AdminPluginsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/skills': typeof AdminSkillsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/plugins/$slug': typeof PluginsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/announcements': typeof AnnouncementsRoute
  '/contact': typeof ContactRoute
  '/ecosystem': typeof EcosystemRoute
  '/hire': typeof HireRoute
  '/plugins': typeof PluginsRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/reviews': typeof ReviewsRoute
  '/servers': typeof ServersRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tickets': typeof TicketsRoute
  '/websites': typeof WebsitesRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/plugins': typeof AdminPluginsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/skills': typeof AdminSkillsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/plugins/$slug': typeof PluginsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/announcements'
    | '/contact'
    | '/ecosystem'
    | '/hire'
    | '/plugins'
    | '/projects'
    | '/reviews'
    | '/servers'
    | '/services'
    | '/sitemap.xml'
    | '/tickets'
    | '/websites'
    | '/admin/announcements'
    | '/admin/blog'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/plugins'
    | '/admin/projects'
    | '/admin/reviews'
    | '/admin/services'
    | '/admin/skills'
    | '/admin/testimonials'
    | '/admin/tickets'
    | '/plugins/$slug'
    | '/projects/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/announcements'
    | '/contact'
    | '/ecosystem'
    | '/hire'
    | '/plugins'
    | '/projects'
    | '/reviews'
    | '/servers'
    | '/services'
    | '/sitemap.xml'
    | '/tickets'
    | '/websites'
    | '/admin/announcements'
    | '/admin/blog'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/plugins'
    | '/admin/projects'
    | '/admin/reviews'
    | '/admin/services'
    | '/admin/skills'
    | '/admin/testimonials'
    | '/admin/tickets'
    | '/plugins/$slug'
    | '/projects/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/announcements'
    | '/contact'
    | '/ecosystem'
    | '/hire'
    | '/plugins'
    | '/projects'
    | '/reviews'
    | '/servers'
    | '/services'
    | '/sitemap.xml'
    | '/tickets'
    | '/websites'
    | '/admin/announcements'
    | '/admin/blog'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/plugins'
    | '/admin/projects'
    | '/admin/reviews'
    | '/admin/services'
    | '/admin/skills'
    | '/admin/testimonials'
    | '/admin/tickets'
    | '/plugins/$slug'
    | '/projects/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  ContactRoute: typeof ContactRoute
  EcosystemRoute: typeof EcosystemRoute
  HireRoute: typeof HireRoute
  PluginsRoute: typeof PluginsRouteWithChildren
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ReviewsRoute: typeof ReviewsRoute
  ServersRoute: typeof ServersRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TicketsRoute: typeof TicketsRoute
  WebsitesRoute: typeof WebsitesRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminPluginsRoute: typeof AdminPluginsRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSkillsRoute: typeof AdminSkillsRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminTicketsRoute: typeof AdminTicketsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/websites': {
      id: '/websites'
      path: '/websites'
      fullPath: '/websites'
      preLoaderRoute: typeof WebsitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers': {
      id: '/servers'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof ServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins': {
      id: '/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof PluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire': {
      id: '/hire'
      path: '/hire'
      fullPath: '/hire'
      preLoaderRoute: typeof HireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem': {
      id: '/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof EcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/plugins/$slug': {
      id: '/plugins/$slug'
      path: '/$slug'
      fullPath: '/plugins/$slug'
      preLoaderRoute: typeof PluginsSlugRouteImport
      parentRoute: typeof PluginsRoute
    }
    '/admin/tickets': {
      id: '/admin/tickets'
      path: '/admin/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AdminTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/admin/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/skills': {
      id: '/admin/skills'
      path: '/admin/skills'
      fullPath: '/admin/skills'
      preLoaderRoute: typeof AdminSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/admin/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/admin/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/admin/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/plugins': {
      id: '/admin/plugins'
      path: '/admin/plugins'
      fullPath: '/admin/plugins'
      preLoaderRoute: typeof AdminPluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/admin/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/admin/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/admin/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PluginsRouteChildren {
  PluginsSlugRoute: typeof PluginsSlugRoute
}

const PluginsRouteChildren: PluginsRouteChildren = {
  PluginsSlugRoute: PluginsSlugRoute,
}

const PluginsRouteWithChildren =
  PluginsRoute._addFileChildren(PluginsRouteChildren)

interface ProjectsRouteChildren {
  ProjectsSlugRoute: typeof ProjectsSlugRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsSlugRoute: ProjectsSlugRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  ContactRoute: ContactRoute,
  EcosystemRoute: EcosystemRoute,
  HireRoute: HireRoute,
  PluginsRoute: PluginsRouteWithChildren,
  ProjectsRoute: ProjectsRouteWithChildren,
  ReviewsRoute: ReviewsRoute,
  ServersRoute: ServersRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TicketsRoute: TicketsRoute,
  WebsitesRoute: WebsitesRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminPluginsRoute: AdminPluginsRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSkillsRoute: AdminSkillsRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminTicketsRoute: AdminTicketsRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
